import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./_components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          fontFamily: "Noto Serif JP, serif",
          background: "linear-gradient(to bottom, #FDF6E3, #EDE1D5)",
          minHeight: "100vh",
        }}
        className={`antialiased`}>
        <div className="">
          <Navbar />
          <div className="mb-[32px]">{children}</div>
        </div>
      </body>
    </html>
  );
}
